---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: bamboo-connector
  namespace: connectors
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: bamboo-connector
  chart:
    git: ssh://git@github.com/jakeva/flux-get-started
    ref: master
    path: charts/bamboo-connector
